### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by siculars** [truevault/hipaa-compliance-developers-guide#1]
Hey TrueVault,

This is really a great resource. Thank you for putting it together. My question is on content licensing. Any consideration as to a CC style license, https://creativecommons.org/licenses/ ? 

Many thanks!

**Comment by mattmo** [comment]
Wanted to bump this since it's been awhile. We like this guide as well and wanted to hear what license this is under.

**Comment by VirtualTraveler** [comment]
Another request for the license. what is the status of this content. Some for of CC license seems like a great idea.
